"use strict";

(o,i,e) => { return b(o,e,i,[[44,"Test"]],function(o,e,i){return t(o,"Test","Blub",true,true);}) };
(o,i,e) => { return b(o,e,i,[[42,"444565"]],function(o,e,i){return t(o,"Test","Blub",true,true);}) };
(o,i,e) => { return b(o,e,i,[[1,"first"],[2,"second"],[3,"third"]],function(o,e,i){return (t(o,"Test","Blub",true,true) || n(o,"No Warning",parseInt(i[2]),[true,true]));}) || n(o,"Warning",parseInt(i[2]),[true,true]) };
(o,i,e) => { return b(o,e,i,[[42,"Test"]],function(o,e,i){return t(o,"Warning",i[43],true,true);}) };
(o,i,e) => { return b(o,e,i,[[42,"Test"]],function(o,e,i){return (t(o,"Warning",i[43],true,true));}) };
(o,i,e) => { return b(o,e,i,[[42,"Test"]],function(o,e,i){return t(o,"No Warning",i[42],true,true);}) };
(o,i,e) => { return b(o,e,i,[[42,"Test"]],function(o,e,i){return (t(o,"No Warning",i[42],true,true));}) };
(o,i,e) => { return b(o,e,i,[[1,"first"],[2,"second"],[3,"third"]],function(o,e,i){return (t(o,"Warning",i[4],true,true) || t(o,"No Warning",i[3],true,true));}) && t(o,"Warning",i[2],true,true) };
(o,i,e) => { return r(o,e,i,"+switch",[0],function(o,e,i){return true;}) };
(o,i,e) => { return r(o,e,i,"+switch",[1],function(o,e,i){return true;}) };
(o,i,e) => { return r(o,e,i,"+switch",[2,[4,true],[5,true]],function(o,e,i){return true;}) };
(o,i,e) => { return r(o,e,i,"+switch",[2,[5,true],[2,false]],function(o,e,i){return true;}) };
(o,i,e) => { return r(o,e,i,"+switch",[3,[4,true],1],function(o,e,i){return true;}) };
(o,i,e) => { return r(o,e,i,"+switch",[3,[4,true],0],function(o,e,i){return true;}) };
(o,i,e) => { return r(o,e,i,"+switch",[3,[4,true],0],function(o,e,i){return t(o,"Test","8",true,false);}) };
(o,i,e) => { return r(o,e,i,"+switch",[3,[4,true],0],function(o,e,i){return (t(o,"Test","",true,false));}) };
(o,i,e) => { return n(o,"and",44,[true,true]) };
(o,i,e) => { return r(o,e,i,"allC",[0],function(o,e,i){return (b(o,e,i,[[815,"Field"]],function(o,e,i){return t(o,"Field",i[815],false,false);}));}) };
(o,i,e) => { return (t(o,"Test","Blub",true,true)) };
(o,i,e) => { return ((t(o,"Text",i[123456789],false,true))) };
(o,i,e) => { return t(o,"Fuzzy","Contains",true,false) };
(o,i,e) => { return n(o,"Value",parseInt(i[7]),[false,false,true]) };
(o,i,e) => { return n(o,"Value",-7,[true,false]) };
(o,i,e) => { return n(o,"Value",777,[false,false,false]) };
(o,i,e) => { return t(o,"Name","Bob",true,true) || n(o,"Value",42,[true,true]) };
(o,i,e) => { return t(o,"Name","Bob",true,true) && n(o,"Value",42,[true,true]) };
(o,i,e) => { return t(o,"Name","Bob",true,true) || !n(o,"Value",42,[true,true]) && t(o,"Address","Street",true,false) != n(o,"Salary",1000,[false,false,false]) };
(o,i,e) => { return !(((t(o,"Name","Bob",true,true) || n(o,"Value",42,[true,true])) && t(o,"Address","Street",true,false)) != n(o,"Salary",1000,[false,false,false])) };
(o,i,e) => { return n(o,"42",42,[true,false]) };
(o,i,e) => { return n(o,"0815",42,[true,false]) };
(o,i,e) => { return t(o,"Name","Bob",false,true) != n(o,"Value",42,[true,true]) };
(o,i,e) => { return !t(o,"Name","Bob",false,false) };
